//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EcuafactExpress.Dal.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalInfo
    {
        public long pk { get; set; }
        public long pkFactura { get; set; }
        public string nombre { get; set; }
        public string valor { get; set; }
        public Nullable<int> NumLinea { get; set; }
    
        public virtual SupplierDocument documento { get; set; }
    }
}
