//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecuafact.WebAPI.Dal.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EcuafactEngineEntities : DbContext
    {
        public EcuafactEngineEntities()
            : base("name=EcuafactEngineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<campoAdicional> campoAdicional { get; set; }
        public virtual DbSet<detalle> detalle { get; set; }
        public virtual DbSet<documento> documento { get; set; }
        public virtual DbSet<Emisor> Emisor { get; set; }
        public virtual DbSet<FormaPago> FormaPago { get; set; }
        public virtual DbSet<impuesto> impuesto { get; set; }
        public virtual DbSet<infoFactura> infoFactura { get; set; }
        public virtual DbSet<totalImpuesto> totalImpuesto { get; set; }
    }
}
