//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecuafact.WebAPI.Dal.Core
{
    using Ecuafact.WebAPI.Domain.Entities.Engine;
    using System.Data.Entity;
    using System.Data.Entity.ModelConfiguration.Conventions;
    public partial class EcuafactEngineContext : DbContext
    { 
        public EcuafactEngineContext()
            : base("EcuafactEngineApiDb")
        {
            System.Data.Entity.Database.SetInitializer<EcuafactEngineContext>(null);
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            base.OnModelCreating(modelBuilder);
        }

        #region Entities Set
        public virtual DbSet<LogProceso> LogProceso { get; set; }
        public virtual DbSet<CampoAdicional> CampoAdicional { get; set; }
        public virtual DbSet<Detalle> Detalle { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<Emisor> Emisor { get; set; }
        public virtual DbSet<FormaPago> FormaPago { get; set; }
        public virtual DbSet<Impuesto> Impuesto { get; set; }
        public virtual DbSet<InfoFactura> InfoFactura { get; set; }
        public virtual DbSet<TotalImpuesto> TotalImpuesto { get; set; }
        public virtual DbSet<EmisorTextoInfoAdicional> EmisorTextoInfoAdicional { get; set; }
        #endregion

    }
    public partial class EcuafactEngineContext2 : DbContext
    {
        public EcuafactEngineContext2()
            : base("EcuafactEngineApiDb2")
        {
            System.Data.Entity.Database.SetInitializer<EcuafactEngineContext2>(null);
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            base.OnModelCreating(modelBuilder);
        }

        #region Entities Set
        public virtual DbSet<LogProceso> LogProceso { get; set; }
        public virtual DbSet<CampoAdicional> CampoAdicional { get; set; }
        public virtual DbSet<Detalle> Detalle { get; set; }
        public virtual DbSet<Documento> Documento { get; set; }
        public virtual DbSet<Emisor> Emisor { get; set; }
        public virtual DbSet<FormaPago> FormaPago { get; set; }
        public virtual DbSet<Impuesto> Impuesto { get; set; }
        public virtual DbSet<InfoFactura> InfoFactura { get; set; }
        public virtual DbSet<TotalImpuesto> TotalImpuesto { get; set; }
        public virtual DbSet<EmisorTextoInfoAdicional> EmisorTextoInfoAdicional { get; set; }
        #endregion

    }
}
