//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecuafact.WebAPI.Dal.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emisor
    {
        public int Id { get; set; }
        public string RUC { get; set; }
        public string RazonSocial { get; set; }
        public string NombreComercial { get; set; }
        public string DireccionMatriz { get; set; }
        public bool EsContribuyenteEspecial { get; set; }
        public string NoResolucion { get; set; }
        public bool ObligadoContabilidad { get; set; }
        public string Logo { get; set; }
        public string CertificadoDigital { get; set; }
        public string Clave { get; set; }
        public int TipoEmision { get; set; }
        public int TipoAmbiente { get; set; }
        public string Version { get; set; }
        public string Autorizacion { get; set; }
        public bool Estado { get; set; }
        public string PortalClientes { get; set; }
        public string EmailNotificacion { get; set; }
        public string HoraInicio { get; set; }
        public Nullable<int> Frecuencia { get; set; }
        public string ClaveSRI { get; set; }
    }
}
