//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecuafact.WebAPI.Domain.Entities.Engine
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("documento")]
    public partial class Documento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Documento()
        {
            this.campoAdicional = new List<CampoAdicional>();
            this.detalle = new List<Detalle>();
            this.FormaPago = new List<FormaPago>();
            this.infoFactura = new List<InfoFactura>();
        }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        public long pk { get; set; }
        public string PkDocumento { get; set; }
        public int? SecuencialUltimoProceso { get; set; }
        public string version { get; set; }
        public string id { get; set; }
        public string ambiente { get; set; }
        public string tipoEmision { get; set; }
        public string razonSocial { get; set; }
        public string nombreComercial { get; set; }
        public string ruc { get; set; }
        public string claveAcceso { get; set; }
        public string codDoc { get; set; }
        public string estab { get; set; }
        public string ptoEmi { get; set; }
        public string secuencial { get; set; }
        public string dirMatriz { get; set; }
        public string numeroautorizacion { get; set; }
        public int? Estado { get; set; }
        public string StrEstado { get; set; }
        public string fechaAutorizacion { get; set; }
        public System.DateTime? FechaIngreso { get; set; }
        public System.DateTime? FechaUltimoIntento { get; set; }
        public System.DateTime? FechaRecepcionCorreo { get; set; }
        public System.DateTime? FechaEnvioCorreo { get; set; }
        public System.DateTime? FechaVisualizaciónCliente { get; set; }
        public System.DateTime? FechaReenvioCorreo { get; set; }
        public string emails { get; set; }
        public decimal? PorcentajeDescuento { get; set; }
        public short? EstadoProceso { get; set; }
        public System.DateTime? FechaHibernacion { get; set; }
        public string UsuarioIngreso { get; set; }
        public System.DateTime? FechaEnvio { get; set; }
        public string PDF { get; set; }
        public string XML { get; set; }
        public string MSG { get; set; }
        public string IDMAIL { get; set; }
        public string CodDoc2 { get; set; }
        public string XMLC { get; set; }
        public string PDFC { get; set; }
        public int? Prioridad { get; set; }
        public int? idDeducible { get; set; }
        public string Destino { get; set; }
        public string Origen { get; set; }
        public short? ResultadoEnviado { get; set; }
        public short? Replicado { get; set; }
        public short? Validado { get; set; }
        public bool? AutorizarAhora { get; set; }
        public int? EstadoExtra1 { get; set; }
        public System.DateTime? FechaEstadoExtra1 { get; set; }
        public int? EstadoExtra2 { get; set; }
        public DateTime? FechaEstadoExtra2 { get; set; }
        public string EstadoExtraObservacion1 { get; set; }
        public string EstadoExtraObservacion2 { get; set; }
        public int? numregistros { get; set; }
        public bool? MigracionNube { get; set; }
        public string ErrorMigracion { get; set; }
        public bool? MigracionRegion { get; set; }
        public string ErrorMigracionRegion { get; set; }
        public bool? Offline { get; set; }
        public System.DateTime? FechaEnvioSRI { get; set; }
        public string CodSucursal { get; set; }
        public short? EstadoUltimaGestion { get; set; }
        public System.DateTime? FechaUltimaGestion { get; set; }
        public bool? DatosRecepcionEnviados { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<CampoAdicional> campoAdicional { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<Detalle> detalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<FormaPago> FormaPago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<InfoFactura> infoFactura { get; set; }
    }
}
