//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecuafact.WebAPI.Domain.Entities.Engine
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("totalImpuesto")]
    public partial class TotalImpuesto
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Required]
        public long pk { get; set; }
        public long pkInfoFactura { get; set; }
        public string codigo { get; set; }
        public string codigoPorcentaje { get; set; }
        public decimal baseImponible { get; set; }
        public decimal? tarifa { get; set; }
        public decimal valor { get; set; }
        public string codDocSustento { get; set; }
        public string numDocSustento { get; set; }
        public string fechaEmisionDocSustento { get; set; }
        public decimal? descuentoAdicional { get; set; }
    
        public virtual InfoFactura infoFactura { get; set; }
    }
}
