//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecuafact.WebAPI.ConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesReport
    {
        public long Id { get; set; }
        public long IssuerId { get; set; }
        public string RUC { get; set; }
        public Nullable<System.DateTime> IssuedOn { get; set; }
        public string DocumentTypeCode { get; set; }
        public string DocumentType { get; set; }
        public string EstablishmentCode { get; set; }
        public string IssuePointCode { get; set; }
        public string Sequential { get; set; }
        public string DocumentNumber { get; set; }
        public string AuthorizationNumber { get; set; }
        public string AuthorizationDate { get; set; }
        public string ContributorName { get; set; }
        public decimal Base0 { get; set; }
        public decimal Base12 { get; set; }
        public decimal IVA { get; set; }
        public decimal Total { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public Nullable<long> RetentionId { get; set; }
        public string RetentionContributorRUC { get; set; }
        public string RetentionContributor { get; set; }
        public string RetentionIssuedOn { get; set; }
        public string RetentionNumber { get; set; }
        public string RetentionAuthorizationNumber { get; set; }
        public string RetentionReferenceType { get; set; }
        public string RetentionReferenceNumber { get; set; }
        public string RetentionReferenceDate { get; set; }
        public string Retention104TaxCode { get; set; }
        public Nullable<decimal> RetentionTaxBase { get; set; }
        public Nullable<decimal> RetentionTaxRate { get; set; }
        public Nullable<decimal> RetentionTaxValue { get; set; }
        public string RetentionVatCode { get; set; }
        public Nullable<decimal> RetentionVatBase { get; set; }
        public Nullable<int> RetentionVatRate { get; set; }
        public Nullable<decimal> RetentionVatValue { get; set; }
        public string RetentionISDCode { get; set; }
        public Nullable<decimal> RetentionISDBase { get; set; }
        public Nullable<int> RetentionISDRate { get; set; }
        public Nullable<decimal> RetentionISDValue { get; set; }
        public string RetentionReason { get; set; }
        public string RetentionDescription { get; set; }
        public string RetentionNotes { get; set; }
        public string RetentionSupplierRUC { get; set; }
        public string RetentionSupplier { get; set; }
        public Nullable<System.DateTime> RetentionDate { get; set; }
    }
}
